// Auto-generated from D:\Ghoomar\Photos\Food
// WoZ = without zircoat (plainer plate), Z = with zircoat (styled plate)
// Rule: prefer (Z) version when both exist; skip (WoZ) duplicates.

export const CATEGORIES = [
  'ALL',
  'Ghoomar Thali',
  'Kachoris',
  'Rajasthani Snacks',
  'Chaats & More',
  'Churma Varieties',
  'Paneer Delicacies',
  'Kadhi Varieties',
  'Gatta Dishes',
  'Rajasthani Sabzis',
  'Traditional Khichda',
  'Heritage Dal',
  'Indian Breads',
  'Flavored Rice',
  'Beverages',
  'Raitas',
  'Chutneys & Achaars',
  'Rajasthani Sweets',
  'Seasonal Halwas',
];

let _id = 1;
const m = (name, cat, img, desc = '', tags = []) => ({ id: _id++, name, category: cat, image: img, description: desc, tags });

export const MENU_ITEMS = [
  // ── Ghoomar Thali ──
  m('Ghoomar Thali', 'Ghoomar Thali', '/images/menu/Ghoomar Thali/IMG_4721.webp',
    'Our signature royal spread — a curated ensemble of Rajasthan\'s finest on a gleaming silver platter.',
    ['Signature', 'Royal Experience', '18+ Dishes']),

  // ── Kachoris ──
  m('Pyaaz Kachori', 'Kachoris', '/images/menu/Kachoris/Pyaaz Kachori (Z).webp',
    'Flaky golden pastry stuffed with spiced onions — the pride of Jodhpur\'s street kitchens.', ['Jodhpur Special', 'Street Classic']),
  m('Dal Kachori', 'Kachoris', '/images/menu/Kachoris/Dal Kachori (Z).webp',
    'Crisp shell filled with herbed lentils, served hot with chutneys.', ['Traditional', 'Vegetarian']),
  m('Aloo Kachori', 'Kachoris', '/images/menu/Kachoris/Aloo Kachori (Z).webp',
    'Deep-fried puffed bread packed with spiced potato filling.', ['Comfort Food', 'Vegetarian']),
  m('Mattar Kachori', 'Kachoris', '/images/menu/Kachoris/Mattar Kachori (Z).webp',
    'Green pea kachori spiced with fennel and coriander.', ['Seasonal', 'Vegetarian']),

  // ── Rajasthani Snacks ──
  m('Ajmeri Dahi Vada', 'Rajasthani Snacks', '/images/menu/Rajasthani Snacks/Ajmeri Dahi Vada (Z).webp',
    'Soft lentil dumplings bathed in chilled yogurt, topped with tangy chutneys.', ['Ajmer Special', 'Vegetarian']),
  m('Jodhpuri Mirchi Vada', 'Rajasthani Snacks', '/images/menu/Rajasthani Snacks/Jodhpuri Mirchi Vada (Z).webp',
    'Large green chilies stuffed with spiced potatoes, battered and deep-fried.', ['Jodhpur Classic', 'Spicy']),
  m('Aloo Kofta', 'Rajasthani Snacks', '/images/menu/Rajasthani Snacks/Aloo Kofta (Z).webp',
    'Potato dumplings in rich gravy — humble royalty from the desert kitchens.', ['Vegetarian', 'Traditional']),
  m('Crispy Bati', 'Rajasthani Snacks', '/images/menu/Rajasthani Snacks/Crispy Bati (Z).webp',
    'Stone-baked wheat rounds, cracked open and drowned in pure desi ghee.', ['Dal Bati Companion', 'Traditional']),
  m('Jaipuri Dahi Vada', 'Rajasthani Snacks', '/images/menu/Rajasthani Snacks/Jaipuri Dahi Vada.webp',
    'Jaipur-style dahi vada with a generous pour of tamarind and mint chutney.', ['Jaipur Special', 'Vegetarian']),
  m('Kela Kofta', 'Rajasthani Snacks', '/images/menu/Rajasthani Snacks/Kela Kofta.webp',
    'Raw banana dumplings simmered in aromatic Rajasthani gravy.', ['Vegetarian', 'Heritage Recipe']),
  m('Bikaneri Moongdal Mangodi', 'Rajasthani Snacks', '/images/menu/Rajasthani Snacks/Bikaneri Moongdal Mangodi.webp',
    'Sun-dried lentil nuggets from Bikaner, cooked with spices and fresh yogurt.', ['Bikaner Special', 'Vegetarian']),

  // ── Chaats & More ──
  m('Dahi Mogra Chaat', 'Chaats & More', '/images/menu/Chaats & More/Dahi Mogra Chaat.webp',
    'Royal jasmine-inspired chaat — layered with yogurt, sev, and sweet tamarind.', ['Street Royalty', 'Vegetarian']),

  // ── Churma Varieties ──
  m('Rajwadi Churma', 'Churma Varieties', '/images/menu/Churma Varieties/Rajwadi Churma (Dry Fruit).webp',
    'Coarse wheat churma enriched with dry fruits and pure ghee.', ['Royal Sweet', 'Traditional']),
  m('Gulab Ka Churma', 'Churma Varieties', '/images/menu/Churma Varieties/Gulab Ka Churma.webp',
    'Fragrant rose-infused churma, a dessert reminiscent of palace gardens.', ['Festival Special', 'Floral']),
  m('Mawa Churma', 'Churma Varieties', '/images/menu/Churma Varieties/Mawa Churma.webp',
    'Milk-solid enriched churma with a melt-in-the-mouth sweetness.', ['Rich', 'Festive']),
  m('Pineapple Churma', 'Churma Varieties', '/images/menu/Churma Varieties/Pineapple Churma.webp',
    'A modern royal twist — pineapple churma with tropical sweetness.', ['Contemporary', 'Sweet']),

  // ── Paneer Delicacies ──
  m('Hariyali Paneer', 'Paneer Delicacies', '/images/menu/Paneer Delicacies/Hariyali Paneer.webp',
    'Cottage cheese cubes in vibrant green herb gravy — fresh, aromatic, royal.', ['Vegetarian', 'Chef\'s Special']),

  // ── Kadhi Varieties ──
  m('Jodhpuri Kadhi', 'Kadhi Varieties', '/images/menu/Kadhi Varieties/Jodhpuri Kadhi.webp',
    'Tangy yogurt kadhi with fried pakoras — the comfort dish of Marwar\'s kitchens.', ['Jodhpur Classic', 'Vegetarian']),
  m('Hariyali Palak Kadhi', 'Kadhi Varieties', '/images/menu/Kadhi Varieties/Hariyali Palak Kadhi.webp',
    'Spinach-enriched kadhi with a vibrant green hue and earthy depth.', ['Spinach Special', 'Vegetarian']),

  // ── Gatta Dishes ──
  m('Besan Gatta Curry', 'Gatta Dishes', '/images/menu/Gatta Dishes/Besan Gatta Curry.webp',
    'Gram flour dumplings in spiced yogurt curry — ancestral Rajasthani comfort.', ['Traditional', 'Vegetarian']),
  m('Besan Gatta Masala', 'Gatta Dishes', '/images/menu/Gatta Dishes/Besan Gatta Masala (Z).webp',
    'Gatta coated in dry-roasted masala — bold, aromatic, addictive.', ['Heritage Recipe', 'Vegetarian']),
  m('Govind Gatta', 'Gatta Dishes', '/images/menu/Gatta Dishes/Govind Gatta.webp',
    'Stuffed gatta with a rich filling, named after the divine spirit of Rajasthan.', ['Royal', 'Vegetarian']),
  m('Jodhpuri Gatta', 'Gatta Dishes', '/images/menu/Gatta Dishes/Jodhpuri Gatta.webp',
    'Jodhpur-style gatta with a robust spice profile and creamy gravy.', ['Jodhpur Special', 'Vegetarian']),
  m('Pudhina Gatta', 'Gatta Dishes', '/images/menu/Gatta Dishes/Pudhina Gatta.webp',
    'Mint-infused gatta — a refreshing, aromatic take on the desert classic.', ['Refreshing', 'Vegetarian']),

  // ── Rajasthani Sabzis ──
  m('Aloo Pyaaz Ki Sabzi', 'Rajasthani Sabzis', '/images/menu/Rajasthani Sabzis/Aloo Pyaaz Ki Sabzi.webp',
    'Potato and onion sabzi cooked in traditional Rajasthani spices.', ['Home Style', 'Vegetarian']),
  m('Bikaneri Sev Tamatar', 'Rajasthani Sabzis', '/images/menu/Rajasthani Sabzis/Bikaneri Sev Tamatar.webp',
    'Tangy tomato curry with crispy sev — Bikaner\'s beloved street dish.', ['Bikaner Special', 'Vegetarian']),
  m('Bhindi Pyaaz Ro Saag', 'Rajasthani Sabzis', '/images/menu/Rajasthani Sabzis/Bhindi Pyaaz Ro Saag.webp',
    'Okra and onion stir-fried in desert spices, earthy and satisfying.', ['Traditional', 'Vegetarian']),
  m('Methi Mattar Malai', 'Rajasthani Sabzis', '/images/menu/Rajasthani Sabzis/Methi Mattar Malai.webp',
    'Fenugreek and green peas in cream — a royal sabzi of delicate bitterness and richness.', ['Rich', 'Vegetarian']),
  m('Lauki Kofta', 'Rajasthani Sabzis', '/images/menu/Rajasthani Sabzis/Lauki Kofta.webp',
    'Bottle gourd koftas in a warm, spiced tomato gravy.', ['Healthy', 'Vegetarian']),
  m('Gobhi Mattar Masala', 'Rajasthani Sabzis', '/images/menu/Rajasthani Sabzis/Gobhi Mattar Masala.webp',
    'Cauliflower and green peas in robust whole-spice masala.', ['Classic', 'Vegetarian']),
  m('Ghiya Palak Kofta', 'Rajasthani Sabzis', '/images/menu/Rajasthani Sabzis/Ghiya Palak Kofta.webp',
    'Tender bottle gourd and spinach koftas in a silky gravy.', ['Wholesome', 'Vegetarian']),
  m('Sarso Ka Saag', 'Rajasthani Sabzis', '/images/menu/Rajasthani Sabzis/Sarso Ka Saag.webp',
    'Slow-cooked mustard greens — a winter classic of the royal heartland.', ['Winter Special', 'Vegetarian']),
  m('Mix Veg', 'Rajasthani Sabzis', '/images/menu/Rajasthani Sabzis/Mix Veg (2).webp',
    'Seasonal vegetables cooked in Rajasthani masala, vibrant and hearty.', ['Seasonal', 'Vegetarian']),
  m('Mangodi Methi Ri Sabji', 'Rajasthani Sabzis', '/images/menu/Rajasthani Sabzis/Mangodi Methi Ri Sabji.webp',
    'Dried lentil nuggets with fenugreek — a desert pantry classic.', ['Desert Pantry', 'Vegetarian']),

  // ── Traditional Khichda ──
  m('Ghoomar Shahi Khichda', 'Traditional Khichda', '/images/menu/Traditional Khichda/Ghoomar Shahi Khichda.webp',
    'Our signature royal khichda — slow-cooked rice and lentil porridge, fit for a maharaja.', ['Signature', 'Royal']),
  m('Bajra Khichda', 'Traditional Khichda', '/images/menu/Traditional Khichda/Bajra Khichda.webp',
    'Rustic pearl millet khichda — the sustenance of Rajasthan\'s desert warriors.', ['Traditional', 'Wholesome']),
  m('Marwadi Khichda', 'Traditional Khichda', '/images/menu/Traditional Khichda/Marwadi Khichda (Z).webp',
    'Marwar-style khichda with whole spices and pure ghee tempering.', ['Marwar Classic', 'Vegetarian']),

  // ── Heritage Dal ──
  m('Dal Panchmel', 'Heritage Dal', '/images/menu/Heritage Dal/Dal Panchmel.webp',
    'Five lentils cooked together with whole spices — the ceremonial dal of royal kitchens.', ['Royal Heritage', 'Vegetarian']),
  m('Dal Rajwadi', 'Heritage Dal', '/images/menu/Heritage Dal/Dal Rajwadi.webp',
    'Rich, ghee-tempered dal slow-cooked in the Rajwadi tradition.', ['Heritage', 'Vegetarian']),
  m('Dal Alishaan', 'Heritage Dal', '/images/menu/Heritage Dal/Dal Alishaan.webp',
    'Grand dal enriched with cream and exotic spices — a truly royal indulgence.', ['Luxurious', 'Vegetarian']),
  m('Dal Bikaneri', 'Heritage Dal', '/images/menu/Heritage Dal/Dal Bikaneri.webp',
    'Bikaner\'s signature lentil preparation with bold, aromatic spices.', ['Bikaner Special', 'Vegetarian']),
  m('Dal Tadka', 'Heritage Dal', '/images/menu/Heritage Dal/Dal Tadka.webp',
    'Yellow lentils with a crackling cumin and garlic tadka — timeless and satisfying.', ['Classic', 'Vegetarian']),
  m('Dal Fry', 'Heritage Dal', '/images/menu/Heritage Dal/Dal Fry.webp',
    'Fried lentil preparation with a rich, buttery tempering.', ['Popular', 'Vegetarian']),
  m('Dal Marwadi', 'Heritage Dal', '/images/menu/Heritage Dal/Dal Marwadi.webp',
    'Marwad-style dal with whole red chilies and rustic earthiness.', ['Marwar Style', 'Vegetarian']),
  m('Hari Mirch Moong Dal', 'Heritage Dal', '/images/menu/Heritage Dal/Hari Mirch Moong Daal.webp',
    'Yellow moong dal with fresh green chilies — light, spiced, and aromatic.', ['Light', 'Vegetarian']),

  // ── Indian Breads ──
  m('Bajra Roti', 'Indian Breads', '/images/menu/Bajra & More Indian Breads/Bajra Roti.webp',
    'Rustic dark millet flatbread, stone-ground and hand-pressed. The bread of warriors and kings.', ['Ancient Grain', 'Traditional']),
  m('Ajwain Poori', 'Indian Breads', '/images/menu/Bajra & More Indian Breads/Ajwain Poori.webp',
    'Carom-seed-spiced deep-fried bread — aromatic, crisp, and irresistible.', ['Deep Fried', 'Spiced']),
  m('Bedmi Poori', 'Indian Breads', '/images/menu/Bajra & More Indian Breads/Bedmi Poori.webp',
    'Lentil-stuffed poori from the alleys of Rajasthan — hearty and flavourful.', ['Stuffed Bread', 'Traditional']),
  m('Methi Poori', 'Indian Breads', '/images/menu/Bajra & More Indian Breads/Methi Poori.webp',
    'Fenugreek-infused poori with a pleasantly bitter, herby aroma.', ['Herbed', 'Vegetarian']),
  m('Palak Poori', 'Indian Breads', '/images/menu/Bajra & More Indian Breads/Palak Poori.webp',
    'Vibrant green spinach poori — as beautiful as it is wholesome.', ['Spinach', 'Vegetarian']),
  m('Plain Paratha', 'Indian Breads', '/images/menu/Bajra & More Indian Breads/Plain Paratha.webp',
    'Whole wheat layered flatbread cooked with a generous brush of ghee.', ['Classic', 'Vegetarian']),
  m('Jwaar Ki Roti', 'Indian Breads', '/images/menu/Bajra & More Indian Breads/Jwaar Ki Roti.webp',
    'Sorghum flatbread — ancient, nutritious, and authentically Rajasthani.', ['Ancient Grain', 'Gluten-Aware']),
  m('Makka Roti', 'Indian Breads', '/images/menu/Bajra & More Indian Breads/Makka Roti.webp',
    'Corn flour flatbread, best enjoyed with sarso ka saag in royal style.', ['Corn Bread', 'Winter Favourite']),

  // ── Flavored Rice ──
  m('Jeera Rice', 'Flavored Rice', '/images/menu/Flavored Rice/Jeera Rice.webp',
    'Fluffy basmati rice tempered with whole cumin — subtly fragrant, eternally comforting.', ['Classic', 'Vegetarian']),
  m('Jodhpuri Gatta Pulav', 'Flavored Rice', '/images/menu/Flavored Rice/Jodhpuri Gatta Pulav.webp',
    'Fragrant pulav studded with gatta — a royal union of Rajasthani classics.', ['Jodhpur Special', 'Vegetarian']),
  m('Moti Pulav', 'Flavored Rice', '/images/menu/Flavored Rice/Moti Pulav.webp',
    'Pearl pulav with saffron, dry fruits, and whole spices — fit for royal banquets.', ['Royal', 'Saffron Infused']),
  m('Shahi Rice', 'Flavored Rice', '/images/menu/Flavored Rice/Shahi Rice.webp',
    'Imperial rice cooked with cream, nuts, and aromatic spices.', ['Imperial', 'Luxurious']),
  m('Veg Pulav', 'Flavored Rice', '/images/menu/Flavored Rice/Veg Pulav.webp',
    'Seasonal vegetables and basmati rice cooked together in one royal pot.', ['One Pot', 'Vegetarian']),
  m('Lemon Rice', 'Flavored Rice', '/images/menu/Flavored Rice/Lemon Rice.webp',
    'Zesty lemon rice with a tempering of mustard seeds and curry leaves.', ['Refreshing', 'Light']),

  // ── Beverages ──
  m('Ghoomar Thandai', 'Beverages', '/images/menu/Beverages/Ghoomar Thandai.webp',
    'Our signature chilled milk drink with saffron, rose, and exotic spices — the taste of Holi.', ['Signature', 'Chilled', 'Festival Drink']),
  m('Boondi Chhach', 'Beverages', '/images/menu/Beverages/Boondi Chhach.webp',
    'Hand-churned buttermilk with floating boondi and roasted cumin — the desert\'s cooler.', ['Traditional', 'Digestive']),
  m('Pudina Chhach', 'Beverages', '/images/menu/Beverages/Pudina Chhach.webp',
    'Cool mint buttermilk — refreshing and perfect for hot summer afternoons.', ['Refreshing', 'Mint']),
  m('Jeera Masala Chhach', 'Beverages', '/images/menu/Beverages/Jeera Masala Chhach.webp',
    'Spiced cumin buttermilk that soothes and refreshes simultaneously.', ['Spiced', 'Digestive']),
  m('Nimbu Shikanji', 'Beverages', '/images/menu/Beverages/Nimbu Shikanji.webp',
    'Royal lemonade with black salt and spices — Rajasthan\'s centuries-old thirst quencher.', ['Citrus', 'Refreshing']),
  m('Kewda Sherbat', 'Beverages', '/images/menu/Beverages/Kewda Sherbat.webp',
    'Aromatic kewda flower sherbet — the floral essence of royal court refreshments.', ['Floral', 'Chilled']),
  m('Hot Rabdi', 'Beverages', '/images/menu/Beverages/Hot Rabdi.webp',
    'Thick warm milk reduced to silky richness with cardamom and saffron.', ['Warm', 'Saffron Infused']),
  m('Sherbat Doodh Gulab', 'Beverages', '/images/menu/Beverages/Sherbat Doodh Gulab.webp',
    'Rose milk sherbet — sweet, chilled, and deeply fragrant.', ['Rose', 'Chilled']),
  m('Vegetable Shorba', 'Beverages', '/images/menu/Beverages/Vegetable Shorba.webp',
    'Spiced vegetable broth — a warming royal soup to begin the feast.', ['Starter', 'Warm']),

  // ── Raitas ──
  m('Bikaneri Veg Raita', 'Raitas', '/images/menu/Raitas/Bikaneri Veg Raita.webp',
    'Bikaner-style mixed vegetable raita with a cooling, spiced yogurt base.', ['Bikaner', 'Cooling']),
  m('Jaipuri Cucumber Raita', 'Raitas', '/images/menu/Raitas/Jaipuri Cucumber Raita.webp',
    'Fresh cucumber in chilled yogurt with roasted cumin — Jaipur\'s summer essential.', ['Jaipur Style', 'Light']),
  m('Jhalawadi Boondi Raita', 'Raitas', '/images/menu/Raitas/Jhalawadi Boondi Raita.webp',
    'Crispy boondi soaked in seasoned yogurt — Jhalawar\'s beloved raita.', ['Crispy', 'Cooling']),
  m('Marwadi Fruit Raita', 'Raitas', '/images/menu/Raitas/Marwadi Fruit Raita.webp',
    'Seasonal fruits folded into sweet yogurt — Marwad\'s royal dessert raita.', ['Sweet', 'Fruity']),
  m('Marwadi Plain Raita', 'Raitas', '/images/menu/Raitas/Marwadi Plain Raita.webp',
    'Simple, pure yogurt raita with a pinch of cumin and red chili.', ['Simple', 'Classic']),

  // ── Chutneys & Achaars ──
  m('Hari Chutney', 'Chutneys & Achaars', '/images/menu/Chutneys & Achaars/Hari Chutney (Z).webp',
    'Vibrant green herb chutney — fresh coriander, mint, and green chilies.', ['Herby', 'Spicy']),
  m('Kair Sangri', 'Chutneys & Achaars', '/images/menu/Chutneys & Achaars/Kair Sangri (Z).webp',
    'Wild desert caper berries and beans in aromatic spices — the soul of Rajasthani condiments.', ['Desert Classic', 'Heritage']),
  m('Lahusun Chutney', 'Chutneys & Achaars', '/images/menu/Chutneys & Achaars/Lahusun Chutney (Z).webp',
    'Bold garlic chutney with dried red chilies — fiery and addictive.', ['Garlicky', 'Spicy']),
  m('Mirchi Ke Tapore', 'Chutneys & Achaars', '/images/menu/Chutneys & Achaars/Mirchi Ke Tapore (Z).webp',
    'Sun-dried chili achaar — concentrated Rajasthani heat preserved in spiced oil.', ['Fiery', 'Preserved']),

  // ── Rajasthani Sweets ──
  m('Rabdi Malpua', 'Rajasthani Sweets', '/images/menu/Rajasthani Sweets/Rabdi Malpua.webp',
    'Soft pancakes drenched in sugar syrup, topped with creamy saffron rabdi.', ['Royal Sweet', 'Saffron']),
  m('Jalebi', 'Rajasthani Sweets', '/images/menu/Rajasthani Sweets/Jalebi (3).webp',
    'Crisp honey-orange spirals soaked in warm sugar syrup — an eternal classic.', ['Classic Sweet', 'Crispy']),
  m('Makhane Ki Kheer', 'Rajasthani Sweets', '/images/menu/Rajasthani Sweets/Makhane Ki Kheer.webp',
    'Fox nut pudding in saffron-infused milk — a light, royal dessert.', ['Light', 'Saffron']),
  m('Sewaiyan Kheer', 'Rajasthani Sweets', '/images/menu/Rajasthani Sweets/Sewaiyan Kheer.webp',
    'Vermicelli pudding with cardamom, rose water, and dry fruits.', ['Fragrant', 'Festive']),
  m('Marwadi Fruit Cream', 'Rajasthani Sweets', '/images/menu/Rajasthani Sweets/Marwadi Fruit Cream.webp',
    'Lush seasonal fruits in thick sweetened cream — a decadent royal indulgence.', ['Creamy', 'Fresh Fruits']),

  // ── Seasonal Halwas ──
  m('Moong Dal Halwa', 'Seasonal Halwas', '/images/menu/Seasonal Halwas/Moong Dal Halwa.webp',
    'Slow-roasted yellow lentil halwa with ghee, saffron, and dry fruits — the king of Rajasthani halwas.', ['King of Halwas', 'Ghee Rich']),
  m('Gajar Ka Halwa', 'Seasonal Halwas', '/images/menu/Seasonal Halwas/Gajar Ka Halwa.webp',
    'Winter carrot halwa cooked in milk and ghee — warm, sweet, nostalgic royalty.', ['Winter Special', 'Beloved Classic']),
  m('Gulab Ka Halwa', 'Seasonal Halwas', '/images/menu/Seasonal Halwas/Gulab Ka Halwa.webp',
    'Fragrant rose halwa — the essence of Rajasthan\'s garden culture in a bowl.', ['Floral', 'Delicate']),
  m('Gond Pak Halwa', 'Seasonal Halwas', '/images/menu/Seasonal Halwas/Gond Pak Halwa.webp',
    'Edible gum halwa with dry fruits — a nourishing winter delicacy.', ['Nourishing', 'Winter Warmth']),
  m('Dry Fruit Sooji Halwa', 'Seasonal Halwas', '/images/menu/Seasonal Halwas/Dry Fruit Sooji Halwa.webp',
    'Semolina halwa studded with premium dry fruits and saffron strands.', ['Rich', 'Celebration Sweet']),
  m('Kesariya Boondi Halwa', 'Seasonal Halwas', '/images/menu/Seasonal Halwas/Kesariya Boondi Halwa.webp',
    'Saffron-soaked boondi halwa — golden, fragrant, and deeply Rajasthani.', ['Saffron', 'Traditional']),
  m('Lauki Halwa', 'Seasonal Halwas', '/images/menu/Seasonal Halwas/Lauki Halwa.webp',
    'Bottle gourd halwa cooked with milk and cardamom — light yet indulgent.', ['Light', 'Wholesome']),
  m('Rawa Halwa', 'Seasonal Halwas', '/images/menu/Seasonal Halwas/Rawa Halwa.webp',
    'Classic semolina halwa with ghee and cardamom — puja-special and homely.', ['Classic', 'Comfort']),
];
